services:
  mysql:
    image: mysql:8
    container_name: mysql-fitness-tracker
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fitness_tracker
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  nodejs:
    image: a045895/inf24dw1g02:latest 
    container_name: nodejs-fitness-tracker
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: fitness_tracker
    ports:
      - "3000:3000"
    volumes:
      - .:/server
      - ./db-init.js:/server/db-init.js  
    command: sh -c "node db-init.js && npm start" 
volumes:
  mysql-data:
